---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Сайт должен уведомлять пользователя при потере интернет-соединения или низкой скорости подключения
  - Сайт должен адаптировать контент в альбомной и книжной ориентации
  - Должен использоваться протокол https
  - Пользователь должен иметь возможность создать учетную запись на сайте
  - Пользователь должен иметь возможность войти в ранее созданный аккаунт
  - Пользователь должен иметь возможность выйти из аккаунта
  - Поля формы регистрации должны содержать placeholders
  - Поля ввода пароля и подтверждения пароля должны скрывать вводимые символы
  - Пользователь должен иметь возможность посмотреть введенные символы в поле пароль (кнопка PassEye)
  - На сайте должна быть плашка иформирующая пользователя об установке cookie
  - Пользователь должен иметь возможность ознакомиться с политикой конфиденциальности и дать согласие (или отказаться) на обработку ПД
  - Пользователь должен иметь возможность восстановить данные учетной записи (логин,пароль) если не помнит их.
  - Пользователь должен иметь возможность перейти к оплате товара из корзины
  - Товары в корзине должны сохраняться в течении сессии браузера
  - Сайт должен автоматически загружаться в мобильной версии при использовании мобильного клиента
  - Пользователь должен иметь возможность изменять количество товаров в корзине
  - Товары в корзине должны сохраняться при смене пользователем десктопного клиента на мобильный и наоборот
  - Пользователь должен иметь возможность просматривать информацию об оплаченных заказах
  - У каждого товара должна отображаться его цена.
  - У корзины должен отображаться счетчик товаров
